name:                parse-minecraft
version:             0.1.0.0
github:              "arendsee/parse-minecraft"
license:             MIT
author:              "Zebulun Arendsee"
maintainer:          "zbwrnz@gmail.com"
copyright:           "2019 Zebulun Arendsee"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/arendsee/parse-minecraft#readme>

default-extensions:
  - OverloadedStrings

dependencies:
- base >= 4.7 && < 5
- attoparsec
- bytestring
- utf8-string
- base16-bytestring
- zlib

library:
  source-dirs: src

executables:
  parse-minecraft-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -haddock
    dependencies:
    - parse-minecraft
